### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by grasshide** [qx6ghqkz/gallery-dl-server#56]
Hey there. I think your latest update broke someting:

```
Traceback (most recent call last):
  File "/usr/src/app/venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/src/app/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.12/site-packages/uvicorn/main.py", line 412, in main
    run(
  File "/usr/src/app/venv/lib/python3.12/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/usr/src/app/venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/src/app/venv/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/usr/src/app/venv/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve
    config.load()
  File "/usr/src/app/venv/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/app/venv/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/src/app/gallery-dl-server.py", line 247, in <module>
    os.makedirs(os.path.dirname(log_file), exist_ok=True)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/usr/src/app/logs'
```

**Comment by qx6ghqkz** [comment]
Sorry about that. I need to rework how permissions work inside the container. For now, running as --user 1000:1000 will fix the issue.

**Comment by qx6ghqkz** [comment]
I have now reworked how permissions work inside the Docker container. Unfortunately, it was impossible to avoid making a **breaking change**, which means you'll have to update any Docker run scripts/compose files, but I did my best to minimise the damage.

### Summary of changes
- New environment variables `UID` and `GID` to set user ID and group ID **instead of** `user`
- Folder containing `gallery-dl.conf` now needs to be mounted at `/config` instead of `/etc`
- Recommend using `restart: on-failure` instead of `restart: unless-stopped`

All changes in code can be found [here](https://github.com/qx6ghqkz/gallery-dl-server/commit/42e21910e993a5a298cd2a2db73b6e1c3de51558).

#### Docker Run
```shell
#!/bin/sh

docker run -d \
  --name gdl-server \
  -p 9080:9080 \
  -e UID=1000 \
  -e GID=1000 \
  -v "/path/to/config/folder:/config" \ # `gallery-dl.conf` goes in here
  -v "/path/to/downloads/folder:/gallery-dl" \
  --restart on-failure \
  qx6ghqkz/gallery-dl-server:latest
```

#### Docker Compose
```yaml
services:
  gallery-dl-server:
    image: qx6ghqkz/gallery-dl-server:latest
    container_name: gdl-server
    ports:
      - 9080:9080
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - "/path/to/config/folder:/config" # `gallery-dl.conf` goes in here
      - "/path/to/downloads/folder:/gallery-dl"
    restart: on-failure
```

### Explanation
- The only way to avoid issues was to stop mounting the config directory at `/etc` inside the container, where all of the important user configuration files like `/etc/passwd` and `/etc/group` which contain the user permissions are stored, as those files get overriden by the mount.

- You could use a single file mount `-v "/path/to/gallery-dl.conf:/etc/gallery-dl.conf"` to mount the config file, however that leads to [this issue](https://github.com/moby/moby/issues/15793#issuecomment-135411504) where changes to the file made while the container is running do not propagate to the container. It is best practice to mount the directory containing the config file and other files you need inside the container instead.

- Since there is no way to reliably mount a directory to `/etc` without overriding the files in the image, a new config location was needed. None of the [default locations](https://github.com/mikf/gallery-dl#locations) where gallery-dl searches for the config file were suitable, so I set a custom location `/config/gallery-dl.conf`. This is the new location for the config file and other files.

- In order to change user permissions and ensure the container starts correctly, the [startup script](https://github.com/qx6ghqkz/gallery-dl-server/blob/main/start.sh) has grown in size. The container will exit on startup if it runs into any errors including having invalid permissions and the config folder still being mounted at `/etc` instead of `/config`. I recommend running the container with `--restart on-failure` as this will allow the container to exit properly on startup without restarting, but it will still restart if it runs into any non-exit code 0 errors after startup and will restart with the Docker daemon.
